# Generated by Django 2.0.4 on 2019-02-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rahul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='acprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
