# Generated by Django 2.0.4 on 2019-02-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rahul', '0002_auto_20190202_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
