# Generated by Django 2.0.4 on 2019-03-02 18:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rahul', '0003_auto_20190202_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=tinymce.models.HTMLField(),
        ),
    ]
