bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'$100,000',
  '200000':'$200,000',
  '300000':'$300,000',
  '400000':'$400,000',
  '500000':'$500,000',
  '600000':'$600,000',
  '700000':'$700,000',
  '800000':'$800,000',
  '900000':'$900,000',
  '1000000':'$1M+',
}

state_choices = {
        'Warsaw':'Warsaw',
        'Kraków':'Kraków',
        'Wrocław':'Wrocław',
        'Poznań':'Poznań',
        'Gdańsk':'Gdańsk',
        'Szczecin': 'Szczecin',
        'Bydgoszcz':'Bydgoszcz',
        'Lublin':'Lublin',
        'Gdynia':'Gdynia',
        'Radom': 'Radom',
        'Katowice':'Katowice',
        'Kielce':'Kielce',
        'Zakopane':'Zakopane',
        'New Delhi':'New Delhi',
        'Mumbai':'Mumbai',
        'Kolkata':'Kolkata',
        'Banglore':'Banglore',
        'Bihar':'Bihar',
        'Uttar Pradesh':'Uttar Pradesh',
        'HR':'Haryana',
        'Haryana':'Jammu Kashmir',
        'Himachel Pradesh':'Himachel Pradesh',
        'UttraKhand':'UttraKhand',
        'Kerla':'Kerla',
        'Chenni':'Chenni',
        'Gujrat':'Gujrat',
        'Rajasthan':'Rajasthan',
        'Andhra Pradesh':'Andhra Pradesh',
        'Assam':'Assam',
        'Arunachal Pradesh ':'Arunachal Pradesh ',
        'Chhattisgarh':'Chhattisgarh',
        'Goa':'Goa',
        'Jharkhand':'Jharkhand',
        'Karnataka':'Karnataka',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}